### PR TITLE
new account method

### LINKED ISSUE #4: The system shall be able to create a new account for a customer
NEWACCOUNT <Name>
e.g. NEWACCOUNT Savings
Returns SUCCESS or FAIL

### PR DESCRIPTION
**Pull request by croub**
Please review new account method and amendment to processRequest.

### CODE REVIEW

**Comment by charlottejeynon** [comment]
Hi Christina,
Is there a 'fail' result for the last action? In the 60s lines?
Does this code run fine for you?
Were there any areas in particular you wanted to highlight?

Thanks,
Charlotte

**Comment by croub** [comment]
> Hi Christina,
> Is there a 'fail' result for the last action? In the 60s lines?
> Does this code run fine for you?
> Were there any areas in particular you wanted to highlight?
> 
> Thanks,
> Charlotte

Hi Charlotte,

Yes this runs for me. In which command do you get fail? 
Thanks,
Christina

**Comment by charlottejeynon** [comment]
hi Christina,

I don't get a fail, I mean there is no 'fail' result - where you have a 'success' one? What happens if the user has the wrong details?

Charlotte

**Comment by croub** [comment]
> hi Christina,
> 
> I don't get a fail, I mean there is no 'fail' result - where you have a 'success' one? What happens if the user has the wrong details?
> 
> Charlotte

I'm sorry if I don't get it. 

With my amendments to the current code, we get 2 new commands from the user. 'NEWACCOUNT Current'  AND 'NEWACCOUNT Savings', which both return SUCCESS anything else will return FAIL. This behaviour is tested on my local copy of the code. 

Can you please give me more details on what you expect to work or not work? I'm online on discord if that helps.

Christina

**Comment by SoetZombie** [comment]
> > hi Christina,
> > I don't get a fail, I mean there is no 'fail' result - where you have a 'success' one? What happens if the user has the wrong details?
> > Charlotte
> 
> I'm sorry if I don't get it.
> 
> With my amendments to the current code, we get 2 new commands from the user. 'NEWACCOUNT Current' AND 'NEWACCOUNT Savings', which both return SUCCESS anything else will return FAIL. This behaviour is tested on my local copy of the code.
> 
> Can you please give me more details on what you expect to work or not work? I'm online on discord if that helps.
> 
> Christina

I think Charlotte means if we are guarding against possible fails on the operations.

```
	private String newAccount(CustomerID customer, Account account) {
		customers.get(customer.getKey()).addAccount(account);
		return "SUCCESS";
	}
```

This method always returns success regardless of add account succeeding, the problem I see here is that we are not checking if such account already exists therefore user might end up with 10x savings account. I think the code should check if such account exits and if it does then return some message saying something like "Fail, such account already exists" or something similar.

**Comment by charlottejeynon** [comment]
Hi all,
Yes what Lukas said! Thank you for explaining better than I could :)
Charlotte

**Comment by croub** [comment]
> > > hi Christina,
> > > I don't get a fail, I mean there is no 'fail' result - where you have a 'success' one? What happens if the user has the wrong details?
> > > Charlotte
> > 
> > 
> > I'm sorry if I don't get it.
> > With my amendments to the current code, we get 2 new commands from the user. 'NEWACCOUNT Current' AND 'NEWACCOUNT Savings', which both return SUCCESS anything else will return FAIL. This behaviour is tested on my local copy of the code.
> > Can you please give me more details on what you expect to work or not work? I'm online on discord if that helps.
> > Christina
> 
> I think Charlotte means if we are guarding against possible fails on the operations.
> 
> ```
> 	private String newAccount(CustomerID customer, Account account) {
> 		customers.get(customer.getKey()).addAccount(account);
> 		return "SUCCESS";
> 	}
> ```
> 
> This method always returns success regardless of add account succeeding, the problem I see here is that we are not checking if such account already exists therefore user might end up with 10x savings account. I think the code should check if such account exits and if it does then return some message saying something like "Fail, such account already exists" or something similar.

Thanks for explaining Lukas. I can see that. Is there limit then on how many accounts each customer can have?

**Comment by SoetZombie** [comment]
> > > > hi Christina,
> > > > I don't get a fail, I mean there is no 'fail' result - where you have a 'success' one? What happens if the user has the wrong details?
> > > > Charlotte
> > > 
> > > 
> > > I'm sorry if I don't get it.
> > > With my amendments to the current code, we get 2 new commands from the user. 'NEWACCOUNT Current' AND 'NEWACCOUNT Savings', which both return SUCCESS anything else will return FAIL. This behaviour is tested on my local copy of the code.
> > > Can you please give me more details on what you expect to work or not work? I'm online on discord if that helps.
> > > Christina
> > 
> > 
> > I think Charlotte means if we are guarding against possible fails on the operations.
> > ```
> > 	private String newAccount(CustomerID customer, Account account) {
> > 		customers.get(customer.getKey()).addAccount(account);
> > 		return "SUCCESS";
> > 	}
> > ```
> > 
> > 
> > This method always returns success regardless of add account succeeding, the problem I see here is that we are not checking if such account already exists therefore user might end up with 10x savings account. I think the code should check if such account exits and if it does then return some message saying something like "Fail, such account already exists" or something similar.
> 
> Thanks for explaining Lukas. I can see that. Is there limit then on how many accounts each customer can have?

I don't think we need a limit, but we should prevent duplication so 1 current 1 savings

**Comment by croub** [comment]
Thanks both. @charlottejeynon please reject my pull request for now :)

**Comment by charlottejeynon** [comment]
Can't work out any other way to reject it lol

**Comment by SoetZombie** [comment]
There is no need to close the pr, just request changes and once christine is done she can push a new commit with updated code and you can re-review :)

**Review by charlottejeynon — CHANGES_REQUESTED** [review]
As mentioned!

**Comment by croub** [comment]
@charlottejeynon @SoetZombie new code committed. made quite a few changes. Please do let me know if I'm missing something obvious again 🤣

**Comment by croub** [comment]
Hello @charlottejeynon and @SoetZombie, I have improved the processCommand method after Lukas comments yesterday. It now check for the expected values. everything else remains the same. Do let me know if it needs further reviewing. Thanks!

**Review by charlottejeynon — APPROVED** [review]
good job!

**Review by charlottejeynon — APPROVED** [review]

**Review by charlottejeynon — APPROVED** [review]

**Review by charlottejeynon — APPROVED** [review]

**Pull request merged**
